index:
    path: /
    controller: App\Controller\LoginController::index

registro_manager:
    path: /registroController
    controller: App\Controller\RegistroManager::registrarCliente
    methods: [POST]

listar_titulos:
    path: /listar_titulos
    controller: App\Controller\ListadoTitulosManager::paginaPrincipal
    methods: [GET]
    
mostrar_suscripcion:
    path: /suscripcion
    controller: App\Controller\SuscripcionManager::mostrarSuscripcion
    methods: [GET, POST]

cancelar_suscripcion:
    path: /cancelar_suscripcion
    controller: App\Controller\SuscripcionManager::cancelarSuscripcion
    methods: [GET, POST]
