index:
    path: /
    controller: App\Controller\LoginController::index

registro_manager:
    path: /registroController
    controller: App\Controller\RegistroManager::registrarCliente
    methods: [POST]

lista_titulos:
    path: /lista_titulos
    controller: App\Controller\ListadoTitulosManager::paginaPrincipal

